import { Game } from "@/stores/gameStore";

export const DEFAULT_BOOKMARKS: Omit<Game, "id">[] = [
  {
    name: "Netflix",
    path: "https://www.netflix.com",
    executable: "https://www.netflix.com",
    cover_art: undefined,
    icon: "https://www.google.com/s2/favicons?domain=netflix.com&sz=256",
    platform: "Web",
    category: "Media",
    launch_type: "Url",
  },
  {
    name: "Disney+",
    path: "https://www.disneyplus.com",
    executable: "https://www.disneyplus.com",
    cover_art: undefined,
    icon: "https://www.google.com/s2/favicons?domain=disneyplus.com&sz=256",
    platform: "Web",
    category: "Media",
    launch_type: "Url",
  },
  {
    name: "Amazon Prime Video",
    path: "https://www.primevideo.com",
    executable: "https://www.primevideo.com",
    cover_art: undefined,
    icon: "https://www.google.com/s2/favicons?domain=primevideo.com&sz=256",
    platform: "Web",
    category: "Media",
    launch_type: "Url",
  },
  {
    name: "YouTube",
    path: "https://www.youtube.com",
    executable: "https://www.youtube.com",
    cover_art: undefined,
    icon: "https://www.google.com/s2/favicons?domain=youtube.com&sz=256",
    platform: "Web",
    category: "Media",
    launch_type: "Url",
  },
  {
    name: "Hulu",
    path: "https://www.hulu.com",
    executable: "https://www.hulu.com",
    cover_art: undefined,
    icon: "https://www.google.com/s2/favicons?domain=hulu.com&sz=256",
    platform: "Web",
    category: "Media",
    launch_type: "Url",
  },
  {
    name: "HBO Max",
    path: "https://www.hbomax.com",
    executable: "https://www.hbomax.com",
    cover_art: undefined,
    icon: "https://www.google.com/s2/favicons?domain=hbomax.com&sz=256",
    platform: "Web",
    category: "Media",
    launch_type: "Url",
  },
  {
    name: "Paramount+",
    path: "https://www.paramountplus.com",
    executable: "https://www.paramountplus.com",
    cover_art: undefined,
    icon: "https://www.google.com/s2/favicons?domain=paramountplus.com&sz=256",
    platform: "Web",
    category: "Media",
    launch_type: "Url",
  },
  {
    name: "Apple TV+",
    path: "https://tv.apple.com",
    executable: "https://tv.apple.com",
    cover_art: undefined,
    icon: "https://www.google.com/s2/favicons?domain=tv.apple.com&sz=256",
    platform: "Web",
    category: "Media",
    launch_type: "Url",
  },
  {
    name: "Crunchyroll",
    path: "https://www.crunchyroll.com",
    executable: "https://www.crunchyroll.com",
    cover_art: undefined,
    icon: "https://www.google.com/s2/favicons?domain=crunchyroll.com&sz=256",
    platform: "Web",
    category: "Media",
    launch_type: "Url",
  },
  {
    name: "Twitch",
    path: "https://www.twitch.tv",
    executable: "https://www.twitch.tv",
    cover_art: undefined,
    icon: "https://www.google.com/s2/favicons?domain=twitch.tv&sz=256",
    platform: "Web",
    category: "Media",
    launch_type: "Url",
  },
];

export function getDefaultBookmarks(): Game[] {
  return DEFAULT_BOOKMARKS.map((bookmark, index) => ({
    ...bookmark,
    id: `default_bookmark_${index}`,
  }));
}

